#!/usr/bin/env python3
"""Generate the paper's protocol-paired result tables (docs/PAPER_TABLES.md).

Builds two protocol-paired headline tables plus a full per-config ablation
appendix, entirely from precomputed summary JSONs (no tracker re-runs):

  Table 1 — V2V protocol (DMSTrack-comparable, FP-ignore):
      AMOTA / AMOTP / sAMOTA / MOTA / HOTA / IDS for published anchors,
      our replications of those anchors (precomputed tracks scored through
      our evaluator), our 6 sweep configs' best stream (SABRE + GPEM-polar),
      and the S3 rows (our GPEM filters on DMSTrack's per-CAV PP detections,
      re-scored from KITTI dumps under results/V2V4Real_S3_RESCORE/).

  Table 2 — Ours protocol (FP-counted, with the cross-CAV dual-GT overlap
      spatially deduplicated): same rows, single column set
      (AMOTA / AMOTP / sAMOTA / MOTA / HOTA / IDS).

  Appendix — full 30-stream (6 filters x 5 covariance modes) ablation table
      for each of the 6 sweep configs, with V2V AMOTA, Ours-protocol AMOTA
      and HOTA.

Data sources (all relative to --repo-root):
  - sweep summaries: results/V2V4Real_GPEM_ABLATION_{4SWEEP,CPFT}/<cfg>/test/
        summary_v2v4real_protocol.json  (30 streams, keys end _av_100.0pct)
  - anchor replications: precomputed-track summaries under
        results/V2V4Real_DMSTRACK_MG_*/
        and results/V2V4Real_LF_DEFAULT_BASELINE_*/
  - S3 re-scores: precomputed-track summaries under
        results/V2V4Real_S3_RESCORE/ (generated by run_v2v4real_benchmark.py
        --configs s3_dms_percav_* — see S3_ROWS below)
  - published reference numbers: DMSTrack paper / V2V4Real paper rows as
        mirrored in scripts/v2v4real_leaderboard_table.py (PAPER_ROWS) and
        docs/V2V4REAL_REPRODUCIBILITY_NOTES.md

Every emitted row carries a numbered footnote with its source path so each
number is traceable. Extraction is sanity-checked against known best-stream
values (see EXPECTED_BEST) and the script aborts on mismatch unless
--no-check is given.

Usage:
    python scripts/paper_protocol_tables.py                    # writes docs/PAPER_TABLES.md + .tex
    python scripts/paper_protocol_tables.py --no-tex           # markdown only
    python scripts/paper_protocol_tables.py --out other.md
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Optional

# ---------------------------------------------------------------------------
# Row / source definitions
# ---------------------------------------------------------------------------

# Published reference rows (V2V protocol only — papers publish FP-ignore
# numbers, no HOTA / IDS published for these rows).
#   (label, amota, amotp, samota, mota, source)
PUBLISHED_ROWS = [
    ("Late Fusion + AB3DMOT (published)", 29.28, 51.08, 71.05, 59.89,
     "V2V4Real paper, tracking table (mirrored in "
     "`scripts/v2v4real_leaderboard_table.py::PAPER_ROWS`)"),
    ("CoBEVT + AB3DMOT (published, DMSTrack repro)", 37.16, 57.20, 84.54, 84.14,
     "DMSTrack paper's CoBEVT(*) reproduction row (mirrored in "
     "`scripts/v2v4real_leaderboard_table.py::PAPER_ROWS`; see "
     "`docs/V2V4REAL_REPRODUCIBILITY_NOTES.md`)"),
    ("DMSTrack (published)", 43.52, 57.94, 91.50, 88.32,
     "DMSTrack paper (mirrored in "
     "`scripts/v2v4real_leaderboard_table.py::PAPER_ROWS`)"),
]

# Anchor replications: precomputed baseline tracks scored through our
# evaluator.  (label, summary_path, stream_key, ours_path_or_None)
# ours_path: alternate summary of the SAME tracks used for the Ours-protocol
# metrics when the Table-1 source predates those metric keys (paper_*).
ANCHOR_KEY = "dmstrack_av_100.0pct"
ANCHOR_REPLICATIONS = [
    ("Late Fusion + AB3DMOT (replication, default R, 3D-IoU per-seq)",
     "results/V2V4Real_LF_DEFAULT_BASELINE_2026-05-16_234530/"
     "ab3dmot_late_fusion_default_precomputed_3d/test/summary_v2v4real_protocol.json",
     ANCHOR_KEY, None),
    ("CoBEVT + AB3DMOT (replication, DMSTrack-exact protocol)",
     # HEADTOHEAD run = 37.28 (canonical; ≈ DMSTrack paper's 37.16). The MG run
     # gives 37.34 for the same baseline; both replicate the paper, we pin 37.28.
     "results/V2V4Real_DMSTRACK_HEADTOHEAD_2026-05-15_145623/"
     "cobevt_precomputed_dmstrack_exact/test/summary_v2v4real_protocol.json",
     ANCHOR_KEY, None),
    ("DMSTrack (replication, DMSTrack-exact protocol)",
     # HEADTOHEAD run = 44.27 (canonical; same run as the CoBEVT anchor above).
     "results/V2V4Real_DMSTRACK_HEADTOHEAD_2026-05-15_145623/"
     "dmstrack_precomputed_dmstrack_exact/test/summary_v2v4real_protocol.json",
     ANCHOR_KEY, None),
]

# Our 6 sweep configs. Best stream everywhere is SABRE + GPEM-polar.
#   (short_id, label, summary_path)
BEST_STREAM_KEY = "sabre_gpem_polar_av_100.0pct"
SWEEP_CONFIGS = [
    ("pp_logodds",
     "Ours (SABRE + GPEM-polar) — PP score-0, log\\_odds (score-0 + birth gate)",
     "results/V2V4Real_BENCHMARK_100m_rescore_20260630/pp_score0_gpem_logodds/test/"
     "summary_v2v4real_protocol.json"),
    ("pp_ab3dmot",
     "Ours (SABRE + GPEM-polar) — PP score-0, AB3DMOT (score >= 0.2 floor)",
     "results/V2V4Real_BENCHMARK_100m_rescore_20260630/pp_score0_gpem_ab3dmot/test/"
     "summary_v2v4real_protocol.json"),
    ("cpzs_logodds",
     "Ours (SABRE + GPEM-polar) — CPZS-100m, log\\_odds (score-0 + birth gate)",
     "results/V2V4Real_GPEM_ABLATION_4SWEEP/cp_zeroshot_100m_gpem_logodds/test/"
     "summary_v2v4real_protocol.json"),
    ("cpzs_ab3dmot",
     "Ours (SABRE + GPEM-polar) — CPZS-100m, AB3DMOT (score >= 0.3 floor)",
     "results/V2V4Real_GPEM_ABLATION_4SWEEP/cp_zeroshot_100m_gpem_ab3dmot/test/"
     "summary_v2v4real_protocol.json"),
    ("cpft_logodds",
     "Ours (SABRE + GPEM-polar) — CPft-100m, log\\_odds (score-0 + birth gate)",
     "results/V2V4Real_GPEM_ABLATION_CPFT/cpft_100m_gpem_logodds/test/"
     "summary_v2v4real_protocol.json"),
    ("cpft_ab3dmot",
     "Ours (SABRE + GPEM-polar) — CPft-100m, AB3DMOT (score >= 0.3 floor)",
     "results/V2V4Real_GPEM_ABLATION_CPFT/cpft_100m_gpem_ab3dmot/test/"
     "summary_v2v4real_protocol.json"),
]

# Sanity anchors: known (V2V AMOTA, Ours-protocol AMOTA) of the best stream
# per config.
EXPECTED_BEST = {
    "pp_logodds":   (36.79, 23.34),
    "pp_ab3dmot":   (38.83, 33.78),
    "cpzs_logodds": (38.01, 26.02),
    "cpzs_ab3dmot": (38.83, 33.92),
    "cpft_logodds": (42.12, 38.87),
    "cpft_ab3dmot": (39.60, 37.95),
}
EXPECTED_ANCHORS = {  # V2V AMOTA of selected replications
    "Late Fusion + AB3DMOT (replication, default R, 3D-IoU per-seq)": 37.28,
    "CoBEVT + AB3DMOT (replication, DMSTrack-exact protocol)": 37.28,
    "DMSTrack (replication, DMSTrack-exact protocol)": 44.27,
}

# Ours S3 — GPEM filters running directly on DMSTrack's per-CAV PointPillar
# detections (their detector + per-CAV fusion input, our filters; no
# self-inject except where noted). KITTI MOT dumps re-scored through the
# precomputed-tracks pipeline with the DMSTrack-exact protocol (3D-IoU +
# global tape + AB3DMOT rematching), the same invocation as the anchor
# replications above. Regenerate the summaries with:
#   python scripts/run_v2v4real_benchmark.py \
#       --configs s3_dms_percav_ekf_noinject,s3_dms_percav_ci_noinject,\
#                 s3_dms_percav_sabre_noinject,s3_dms_percav_sabre_quad_autotuned \
#       --output-dir results/V2V4Real_S3_RESCORE
#   (short_id, label, summary_path)
S3_ROWS = [
    # The three legacy no-inject rows run the IMMEDIATE-EMIT lifecycle
    # (min_hits=1, max_age=5) — forensically recovered 2026-06-12 via a
    # bit-identical reproduction (FORENSIC_mh1ma5_cmrekf). Label it: under the
    # FP-ignore V2V protocol immediate emission is near-free recall, so these
    # are NOT apples-to-apples with mh=3/ma=2 rows.
    ("s3_ekf",
     "Ours S3 — GPEM filters on DMSTrack per-CAV PP dets, EKF "
     "(no self-inject; immediate-emit mh=1/ma=5)",
     "results/V2V4Real_S3_RESCORE/s3_dms_percav_ekf_noinject/test/"
     "summary_v2v4real_protocol.json"),
    ("s3_ci",
     "Ours S3 — GPEM filters on DMSTrack per-CAV PP dets, CI "
     "(no self-inject; immediate-emit mh=1/ma=5)",
     "results/V2V4Real_S3_RESCORE/s3_dms_percav_ci_noinject/test/"
     "summary_v2v4real_protocol.json"),
    ("s3_sabre",
     "Ours S3 — GPEM filters on DMSTrack per-CAV PP dets, SABRE "
     "(no self-inject; immediate-emit mh=1/ma=5)",
     "results/V2V4Real_S3_RESCORE/s3_dms_percav_sabre_noinject/test/"
     "summary_v2v4real_protocol.json"),
    ("s3_sabre_quad",
     "Ours S3 — GPEM filters on DMSTrack per-CAV PP dets, "
     "SABRE + GPEM-quadratic (autotuned)",
     "results/V2V4Real_S3_RESCORE/s3_dms_percav_sabre_quad_autotuned/test/"
     "summary_v2v4real_protocol.json"),
]
# Cross-check anchors: V2V AMOTA of the same tracker dumps as independently
# computed by scripts/paper_metrics.py (results/paper_metrics_V2V_noinject.md
# for the three no-inject rows; results/paper_metrics_S3NoNorm_sabre_quad.md
# for the autotuned row). Tolerance 0.1 — the .md path goes through
# build_pooled_tape, this one through the KITTI-dump parser.
EXPECTED_S3 = {
    "s3_ekf":        46.78,
    "s3_ci":         46.70,
    "s3_sabre":      44.33,
    "s3_sabre_quad": 41.97,
}

# Our S4 sweeps re-run with the immediate-emit lifecycle (mh=1/ma=5) — the
# protocol-lever check. Unlike the baselines (whose Ours collapses under
# immediate emission), our SABRE+gate pipeline improves on BOTH protocols.
# Same loader/stream as SWEEP_CONFIGS.
MH1MA5_SWEEP_CONFIGS = [
    ("pp_mh1ma5",
     "Ours (SABRE + GPEM-polar) — PP score-0, AB3DMOT immediate-emit (mh=1/ma=5)",
     "results/V2V4Real_MH1MA5_CHECK/pp_score0_gpem_ab3dmot_mh1ma5/test/"
     "summary_v2v4real_protocol.json"),
    ("cpzs_mh1ma5",
     "Ours (SABRE + GPEM-polar) — CPZS-100m, AB3DMOT immediate-emit (mh=1/ma=5)",
     "results/V2V4Real_MH1MA5_CHECK/cp_zeroshot_100m_gpem_ab3dmot_mh1ma5/test/"
     "summary_v2v4real_protocol.json"),
    ("cpft_mh1ma5",
     "Ours (SABRE + GPEM-polar) — CPft-100m, AB3DMOT immediate-emit (mh=1/ma=5)",
     "results/V2V4Real_MH1MA5_CHECK/cpft_100m_gpem_ab3dmot_mh1ma5/test/"
     "summary_v2v4real_protocol.json"),
]
EXPECTED_MH1MA5 = {
    "pp_mh1ma5":   (38.37, 33.89),
    "cpzs_mh1ma5": (40.98, 33.87),
    "cpft_mh1ma5": (41.62, 39.79),
}

# Baseline counterparts under the same immediate-emit lifecycle (the
# protocol-exploit demonstration: their V2V jumps but their Ours collapses).
# These need a precomputed-track re-score; rows are SKIPPED with a warning
# until the summaries exist (see the mh1ma5_rescore_* configs in
# run_v2v4real_benchmark.py).
MH1MA5_BASELINE_ROWS = [
    ("mh1ma5_cobevt_ekf",
     "CoBEVT + EKF, immediate-emit (mh=1/ma=5)",
     "results/V2V4Real_S3_RESCORE/mh1ma5_cobevt_ekf/test/"
     "summary_v2v4real_protocol.json"),
    ("mh1ma5_cobevt_sabre",
     "CoBEVT + SABRE + GPEM-quadratic, immediate-emit (mh=1/ma=5)",
     "results/V2V4Real_S3_RESCORE/mh1ma5_cobevt_sabre/test/"
     "summary_v2v4real_protocol.json"),
    ("mh1ma5_dms_sabre",
     "Ours S3 — DMS per-CAV PP dets, SABRE + GPEM-quadratic, "
     "immediate-emit (mh=1/ma=5)",
     "results/V2V4Real_S3_RESCORE/mh1ma5_dms_sabre/test/"
     "summary_v2v4real_protocol.json"),
]
EXPECTED_MH1MA5_BASELINE = {  # V2V from results/paper_metrics_mh1ma5_matrix.md
    "mh1ma5_cobevt_ekf":   41.78,
    "mh1ma5_cobevt_sabre": 41.80,
    "mh1ma5_dms_sabre":    46.68,
}

# Appendix stream naming: filter family x covariance mode -> stream key stem.
FILTERS = ["EKF", "CI", "AKF", "PF", "BICI", "SABRE"]
COVS = [("baseline", "baseline"), ("static", "static"),
        ("GPEM-linear", "gpem_linear"), ("GPEM-quadratic", "gpem_quadratic"),
        ("GPEM-polar", "gpem_polar")]


def _stream_key(filt: str, cov_key: str) -> str:
    """summary.json stream key for (filter family, covariance mode)."""
    if filt == "EKF":
        # EKF streams are unprefixed; its static stream is named static_cov.
        stem = "static_cov" if cov_key == "static" else cov_key
    else:
        stem = f"{filt.lower()}_{cov_key}"
    return f"{stem}_av_100.0pct"


# ---------------------------------------------------------------------------
# Loading / formatting helpers
# ---------------------------------------------------------------------------

def load_stream(repo: Path, rel_path: str, key: str) -> Dict:
    with open(repo / rel_path) as f:
        d = json.load(f)
    try:
        return d["results"][key]
    except KeyError:
        raise KeyError(f"stream {key!r} not in {rel_path}") from None


def fv(x: Optional[float], nd: int = 2) -> str:
    return "—" if x is None else f"{x:.{nd}f}"


def fi(x: Optional[float]) -> str:
    return "—" if x is None else str(int(x))


def _hota(r: Dict) -> Optional[float]:
    """HOTA for a summary entry. Prefer the Ours-protocol re-score
    (`paper_hota_mean`, precomputed-tracks evaluator only); fall back to the
    single FP-counted `hota_mean` (computed on the per-vehicle stream,
    pending Ours-protocol re-score — footnoted in both tables)."""
    h = r.get("paper_hota_mean")
    return h if h is not None else r.get("hota_mean")


def _v2v_row(r: Dict, r_ours: Optional[Dict] = None) -> Dict:
    """Table-1 metrics from a summary entry (V2V protocol, FP-ignore).

    HOTA and IDS have no published FP-ignore definition/value, so they are
    sourced from the Ours-protocol (FP-counted) evaluation of the same
    tracks; `r_ours` supplies them when the Table-1 summary predates the
    Ours-protocol metric keys.
    """
    ro = r_ours if r_ours is not None else r
    return {
        "amota":  r.get("v2v4real_amota_mean"),
        "amotp":  r.get("v2v4real_amotp_mean"),
        "samota": r.get("v2v4real_samota_mean"),
        "mota":   r.get("v2v4real_mota_mean"),
        "hota":   _hota(ro),
        "ids":    ro.get("paper_ids_total"),
    }


def _ours_row(r: Dict) -> Dict:
    """Table-2 metrics (Ours protocol: FP-counted, cross-CAV dual-GT overlap
    spatially deduplicated; `paper_*` summary keys)."""
    return {
        "amota":  r.get("paper_amota_mean"),
        "amotp":  r.get("paper_amotp_mean"),
        "samota": r.get("paper_samota_mean"),
        "mota":   r.get("paper_mota_mean"),
        "hota":   _hota(r),
        "ids":    r.get("paper_ids_total"),
    }


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

class FootnoteBank:
    """Auto-numbered footnotes; identical sources share one number."""

    def __init__(self) -> None:
        self._notes: List[str] = []

    def ref(self, text: str) -> str:
        if text not in self._notes:
            self._notes.append(text)
        return f"[^{self._notes.index(text) + 1}]"

    def render(self) -> str:
        return "\n".join(f"[^{i + 1}]: {t}" for i, t in enumerate(self._notes))


def render_table1(rows: List[Dict], fnotes: FootnoteBank) -> str:
    lines = [
        "## Table 1 — DMSTrack (V2V) protocol",
        "",
        "All metrics ×100, 9 V2V4Real test sequences, 3D tracking. The "
        "DMSTrack (V2V) protocol ignores unmatched tracker detections "
        "(FP-ignore), matching the published V2V4Real / DMSTrack evaluation "
        "behavior (`results/EVAL_PROTOCOLS_AND_FIXES.md` §1, §2.1).",
        "",
        "| Method | AMOTA | AMOTP | sAMOTA | MOTA | HOTA* | IDS** |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for row in rows:
        m = row["metrics"]
        ref = fnotes.ref(row["source"])
        lines.append(
            f"| {row['label']}{ref} | {fv(m['amota'])} | {fv(m['amotp'])} | "
            f"{fv(m['samota'])} | {fv(m['mota'])} | {fv(m.get('hota'))} | "
            f"{fi(m.get('ids'))} |"
        )
    lines += [
        "",
        "\\* No FP-ignore HOTA is defined/published, so HOTA is sourced from "
        "the Ours-protocol (FP-counted) evaluation of the same tracks "
        "(FP treatment moves DetA only; AssA is FP-invariant — "
        "`results/EVAL_PROTOCOLS_AND_FIXES.md` §5). For the six sweep "
        "configs, HOTA is computed against per-vehicle GT pending merged-GT "
        "re-score. Published anchor rows have no HOTA (marked —).",
        "",
        "\\*\\* IDS is sourced from the Ours-protocol (FP-counted) "
        "evaluation of the same tracks; IDS is invariant to the "
        "FP-ignore/FP-counted switch on the same GT set "
        "(`results/EVAL_PROTOCOLS_AND_FIXES.md` §4: identical IDS across "
        "stages). IDS unavailable for published rows (not reported in "
        "either paper).",
    ]
    return "\n".join(lines)


def render_table2(rows: List[Dict], fnotes: FootnoteBank) -> str:
    lines = [
        "## Table 2 — Ours protocol",
        "",
        "Ours protocol: FP-counted, with the cross-CAV dual-GT overlap "
        "spatially deduplicated (merged GT).* "
        "Protocol semantics: `results/EVAL_PROTOCOLS_AND_FIXES.md` §1.",
        "",
        "Published anchors are omitted here: published numbers exist only "
        "under the FP-ignore protocol (Table 1), so no published FP-counted "
        "reference is available.",
        "",
        "| Method | AMOTA | AMOTP | sAMOTA | MOTA | HOTA** | IDS |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for row in rows:
        m = row["metrics"]
        ref = fnotes.ref(row["source"])
        lines.append(
            f"| {row['label']}{ref} | {fv(m['amota'])} | {fv(m['amotp'])} | "
            f"{fv(m['samota'])} | {fv(m['mota'])} | {fv(m['hota'])} | "
            f"{fi(m['ids'])} |"
        )
    lines += [
        "",
        "\\* Precomputed-track caveat: the anchor replications and the S3 "
        "rows emit a single tesla-frame track stream and are scored against "
        "the base GT (31 419 rows, no ego augmentation); the six sweep "
        "configs are scored against the cross-CAV deduplicated GT "
        "(≈34.6 k rows). Numbers are therefore strictly comparable within "
        "each group, and indicative (not identical-GT) across groups.",
        "",
        "\\*\\* For the six sweep configs, HOTA is the single FP-counted "
        "value stored per run (`hota_mean`), computed against per-vehicle "
        "GT pending merged-GT re-score; the anchor replications carry the "
        "Ours-protocol re-score (`paper_hota_mean`).",
    ]
    return "\n".join(lines)


def render_appendix(repo: Path, fnotes: FootnoteBank) -> str:
    parts = [
        "## Appendix — full filter × covariance ablation (30 streams per config)",
        "",
        "Per sweep config: every filter family (EKF, CI, AKF, PF, BICI, SABRE) "
        "× covariance mode (baseline, static, GPEM-linear/-quadratic/-polar). "
        "AMOTA / AMOTP / MOTA are reported under both protocols: V2V "
        "(DMSTrack, FP-ignore) and Ours (FP-counted, merged GT). HOTA is the "
        "single FP-counted value (computed against per-vehicle GT pending "
        "merged-GT re-score; no FP-ignore HOTA is defined). IDS comes from "
        "the Ours evaluation and is protocol-invariant "
        "(`results/EVAL_PROTOCOLS_AND_FIXES.md` §4). Lower is better for "
        "AMOTP and IDS. Best value per column in **bold**.",
        "",
    ]
    for short_id, label, rel_path in SWEEP_CONFIGS:
        with open(repo / rel_path) as f:
            results = json.load(f)["results"]
        ref = fnotes.ref(f"`{rel_path}`")
        title = label.replace("Ours (SABRE + GPEM-polar) — ", "")
        parts.append(f"### {title}{ref}")
        parts.append("")
        rows = []
        for filt in FILTERS:
            for cov_label, cov_key in COVS:
                key = _stream_key(filt, cov_key)
                r = results.get(key)
                if r is None:
                    rows.append((filt, cov_label, None))
                    continue
                rows.append((filt, cov_label, {
                    "amota_v2v":  r.get("v2v4real_amota_mean"),
                    "amota_ours": r.get("paper_amota_mean"),
                    "amotp_v2v":  r.get("v2v4real_amotp_mean"),
                    "amotp_ours": r.get("paper_amotp_mean"),
                    "mota_v2v":   r.get("v2v4real_mota_mean"),
                    "mota_ours":  r.get("paper_mota_mean"),
                    "hota":       r.get("hota_mean"),
                    "ids":        r.get("paper_ids_total"),
                }))
        # column-wise best for bolding (AMOTP and IDS: lower is better)
        _COLS = ("amota_v2v", "amota_ours", "amotp_v2v", "amotp_ours",
                 "mota_v2v", "mota_ours", "hota", "ids")
        _LOWER_IS_BETTER = {"amotp_v2v", "amotp_ours", "ids"}
        best = {}
        for col in _COLS:
            vals = [m[col] for _, _, m in rows if m and m[col] is not None]
            if not vals:
                best[col] = None
            else:
                best[col] = min(vals) if col in _LOWER_IS_BETTER else max(vals)
        parts.append(
            "| Filter | Covariance "
            "| AMOTA V2V | AMOTA Ours | AMOTP V2V | AMOTP Ours "
            "| MOTA V2V | MOTA Ours | HOTA | IDS |")
        parts.append("|---|---|---:|---:|---:|---:|---:|---:|---:|---:|")
        for filt, cov_label, m in rows:
            if m is None:
                parts.append(f"| {filt} | {cov_label} |" + " — |" * len(_COLS))
                continue
            cells = []
            for col in _COLS:
                s = (f"{m[col]:d}" if col == "ids" and m[col] is not None
                     else fv(m[col]))
                if m[col] is not None and best[col] is not None and \
                        abs(m[col] - best[col]) < 1e-9:
                    s = f"**{s}**"
                cells.append(s)
            parts.append(f"| {filt} | {cov_label} | " + " | ".join(cells) + " |")
        parts.append("")
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# LaTeX (booktabs) for the two headline tables
# ---------------------------------------------------------------------------

def _tex_escape(s: str) -> str:
    # Row labels already escape underscores; handle the rest minimally.
    return (s.replace("&", "\\&").replace("%", "\\%")
             .replace(">=", "$\\geq$").replace("≥", "$\\geq$")
             .replace("—", "--").replace("×", "$\\times$"))


def render_tex(t1_rows: List[Dict], t2_rows: List[Dict]) -> str:
    L: List[str] = [
        "% Auto-generated by scripts/paper_protocol_tables.py — do not edit.",
        "% Sources for every row: see docs/PAPER_TABLES.md footnotes.",
        "",
        "\\begin{table*}[t]\\centering",
        "\\caption{V2V protocol (DMSTrack-comparable, FP-ignore). HOTA and"
        " IDS are sourced from the FP-counted evaluation of the same tracks"
        " (FP treatment moves DetA only; IDS is invariant to FP treatment)."
        " Published rows report neither.}",
        "\\label{tab:v2v_protocol}",
        "\\begin{tabular}{@{}lrrrrrr@{}}",
        "\\toprule",
        "Method & AMOTA$\\uparrow$ & AMOTP$\\uparrow$ & sAMOTA$\\uparrow$ & "
        "MOTA$\\uparrow$ & HOTA$\\uparrow$ & IDS$\\downarrow$ \\\\ \\midrule",
    ]
    for row in t1_rows:
        m = row["metrics"]
        cells = [_tex_escape(row["label"]), fv(m["amota"]), fv(m["amotp"]),
                 fv(m["samota"]), fv(m["mota"]), fv(m.get("hota")),
                 fi(m.get("ids"))]
        L.append(" & ".join(c.replace("—", "--") for c in cells) + " \\\\")
    L += ["\\bottomrule", "\\end{tabular}", "\\end{table*}", ""]

    L += [
        "\\begin{table*}[t]\\centering",
        "\\caption{Ours protocol: FP-counted, with the cross-CAV dual-GT "
        "overlap spatially deduplicated (merged GT). Sweep-config HOTA is "
        "computed against per-vehicle GT pending merged-GT re-score.}",
        "\\label{tab:ours_protocol}",
        "\\begin{tabular}{@{}lrrrrrr@{}}",
        "\\toprule",
        "Method & AMOTA$\\uparrow$ & AMOTP$\\uparrow$ & sAMOTA$\\uparrow$ & "
        "MOTA$\\uparrow$ & HOTA$\\uparrow$ & IDS$\\downarrow$ \\\\ \\midrule",
    ]
    for row in t2_rows:
        m = row["metrics"]
        cells = [_tex_escape(row["label"]),
                 fv(m["amota"]), fv(m["amotp"]),
                 fv(m["samota"]), fv(m["mota"]),
                 fv(m["hota"]), fi(m["ids"])]
        L.append(" & ".join(c.replace("—", "--") for c in cells) + " \\\\")
    L += ["\\bottomrule", "\\end{tabular}", "\\end{table*}", ""]
    return "\n".join(L)


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repo-root", type=Path,
                    default=Path(__file__).resolve().parent.parent,
                    help="repo root containing results/ (default: this repo)")
    ap.add_argument("--out", default="docs/PAPER_TABLES.md",
                    help="output markdown path, relative to repo root")
    ap.add_argument("--no-tex", action="store_true",
                    help="skip the LaTeX companion file (<out>.tex)")
    ap.add_argument("--no-check", action="store_true",
                    help="skip sanity checks against known best-stream values")
    args = ap.parse_args()
    repo = args.repo_root

    # ---- gather rows -------------------------------------------------------
    t1_rows: List[Dict] = []
    t2_rows: List[Dict] = []

    for label, amota, amotp, samota, mota, src in PUBLISHED_ROWS:
        t1_rows.append({"label": label, "source": src,
                        "metrics": {"amota": amota, "amotp": amotp,
                                    "samota": samota, "mota": mota,
                                    "hota": None, "ids": None}})

    for label, rel_path, key, ours_path in ANCHOR_REPLICATIONS:
        r = load_stream(repo, rel_path, key)
        src = f"`{rel_path}` (key `{key}`)"
        if ours_path is not None:
            r2 = load_stream(repo, ours_path, key)
            # Same tracks: the V2V-protocol number must agree across copies.
            if abs(r2["v2v4real_amota_mean"] - r["v2v4real_amota_mean"]) > 1e-6:
                print(f"WARNING: {label!r}: Table-1/Table-2 source summaries "
                      f"disagree on V2V AMOTA", file=sys.stderr)
            src2 = f"`{ours_path}` (key `{key}`)"
            src1 = f"{src}; HOTA/IDS from same-tracks re-score {src2}"
            t1_rows.append({"label": label, "source": src1,
                            "metrics": _v2v_row(r, r_ours=r2)})
            t2_rows.append({"label": label, "source": src2,
                            "metrics": _ours_row(r2)})
        else:
            t1_rows.append({"label": label, "source": src,
                            "metrics": _v2v_row(r)})
            t2_rows.append({"label": label, "source": src,
                            "metrics": _ours_row(r)})

    for short_id, label, rel_path in SWEEP_CONFIGS:
        r = load_stream(repo, rel_path, BEST_STREAM_KEY)
        src = f"`{rel_path}` (key `{BEST_STREAM_KEY}`)"
        t1_rows.append({"label": label, "source": src, "metrics": _v2v_row(r)})
        t2_rows.append({"label": label, "source": src, "metrics": _ours_row(r)})
        if not args.no_check:
            exp_v2v, exp_ours = EXPECTED_BEST[short_id]
            got_v2v = r["v2v4real_amota_mean"]
            got_ours = r["paper_amota_mean"]
            if abs(got_v2v - exp_v2v) > 0.05 or abs(got_ours - exp_ours) > 0.05:
                print(f"SANITY FAIL {short_id}: expected V2V/Ours "
                      f"{exp_v2v}/{exp_ours}, got {got_v2v:.2f}/{got_ours:.2f}",
                      file=sys.stderr)
                return 2

    for short_id, label, rel_path in MH1MA5_SWEEP_CONFIGS:
        r = load_stream(repo, rel_path, BEST_STREAM_KEY)
        src = f"`{rel_path}` (key `{BEST_STREAM_KEY}`)"
        t1_rows.append({"label": label, "source": src, "metrics": _v2v_row(r)})
        t2_rows.append({"label": label, "source": src, "metrics": _ours_row(r)})
        if not args.no_check:
            exp_v2v, exp_ours = EXPECTED_MH1MA5[short_id]
            got_v2v = r["v2v4real_amota_mean"]
            got_ours = r["paper_amota_mean"]
            if abs(got_v2v - exp_v2v) > 0.05 or abs(got_ours - exp_ours) > 0.05:
                print(f"SANITY FAIL {short_id}: expected V2V/Ours "
                      f"{exp_v2v}/{exp_ours}, got {got_v2v:.2f}/{got_ours:.2f}",
                      file=sys.stderr)
                return 2

    for short_id, label, rel_path in MH1MA5_BASELINE_ROWS:
        if not (repo / rel_path).is_file():
            print(f"[skip] {short_id}: re-score summary not yet at {rel_path} "
                  f"(row omitted until the mh1ma5_rescore_* configs run)",
                  file=sys.stderr)
            continue
        r = load_stream(repo, rel_path, ANCHOR_KEY)
        src = (f"`{rel_path}` (key `{ANCHOR_KEY}`); DMSTrack-exact protocol "
               "re-score; V2V cross-checked against "
               "`results/paper_metrics_mh1ma5_matrix.md`")
        t1_rows.append({"label": label, "source": src, "metrics": _v2v_row(r)})
        t2_rows.append({"label": label, "source": src, "metrics": _ours_row(r)})
        if not args.no_check:
            exp_v2v = EXPECTED_MH1MA5_BASELINE[short_id]
            got_v2v = r["v2v4real_amota_mean"]
            if abs(got_v2v - exp_v2v) > 0.1:
                print(f"SANITY FAIL {short_id}: expected V2V AMOTA "
                      f"{exp_v2v}, got {got_v2v:.2f}", file=sys.stderr)
                return 2

    for short_id, label, rel_path in S3_ROWS:
        r = load_stream(repo, rel_path, ANCHOR_KEY)
        src = (f"`{rel_path}` (key `{ANCHOR_KEY}`); DMSTrack-exact protocol "
               "re-score of the S3 KITTI dumps — V2V AMOTA cross-checked "
               "against `results/paper_metrics_V2V_noinject.md` / "
               "`results/paper_metrics_S3NoNorm_sabre_quad.md`")
        t1_rows.append({"label": label, "source": src, "metrics": _v2v_row(r)})
        t2_rows.append({"label": label, "source": src, "metrics": _ours_row(r)})
        if not args.no_check:
            exp_v2v = EXPECTED_S3[short_id]
            got_v2v = r["v2v4real_amota_mean"]
            if abs(got_v2v - exp_v2v) > 0.1:
                print(f"SANITY FAIL {short_id}: expected V2V AMOTA "
                      f"{exp_v2v}, got {got_v2v:.2f}", file=sys.stderr)
                return 2

    if not args.no_check:
        for row in t1_rows:
            exp = EXPECTED_ANCHORS.get(row["label"])
            if exp is not None and abs(row["metrics"]["amota"] - exp) > 0.05:
                print(f"SANITY FAIL anchor {row['label']!r}: expected AMOTA "
                      f"{exp}, got {row['metrics']['amota']:.2f}", file=sys.stderr)
                return 2

    # ---- render ------------------------------------------------------------
    fnotes = FootnoteBank()
    parts = [
        "# Paper result tables (auto-generated)",
        "",
        "Generated by `scripts/paper_protocol_tables.py` from precomputed "
        "summary JSONs — no tracker re-runs. Regenerate with:",
        "",
        "```bash",
        "python scripts/paper_protocol_tables.py",
        "```",
        "",
        "Protocol definitions and evaluator provenance: "
        "`results/EVAL_PROTOCOLS_AND_FIXES.md` (our scorer is bit-identical "
        "to the cleaned DMSTrack `evaluate.py` at 1.1e-16; the V2V column "
        "preserves the published FP-ignore behavior).",
        "",
        render_table1(t1_rows, fnotes),
        "",
        render_table2(t2_rows, fnotes),
        "",
        render_appendix(repo, fnotes),
        "",
        "## Sources",
        "",
        fnotes.render(),
        "",
    ]
    out_path = repo / args.out
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(parts))
    print(f"wrote {out_path}")

    if not args.no_tex:
        tex_path = out_path.with_suffix(".tex")
        tex_path.write_text(render_tex(t1_rows, t2_rows))
        print(f"wrote {tex_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
